[FEAT] MainPage 생성
9oormthonUNIV-3th-KGU/traveler-client pull request #8
Opened 2024-09-24 07:34 UTC by Jihyeoniiiii

## /home 라우팅 mainpage 생성

-  출발지, 도착지 입력 후 파라미터 넘기기 완료
-  제안하러 가기 버튼 연결 완료
-  현재 위치 목적지 설정 검토 필요!
-  하단 위치 허용 버튼 완료
-  마이페이지 버튼과 내 주변 인기장소 데이터부분은 미완성입니다.
-  입력창은 바텀 시트 만들고 수정할 예정입니다.

> tmap.tsx 출발지입력 현재 위치 설정, 디자인 때문에 수정했습니다. tmap파일 수정부분 확인부탁드립니다!
> app/home/page.tsx 지오코딩 부분 피드백주시면 감사하겠습니다.

![image](https://github.com/user-attachments/assets/29519f88-ded9-452f-bfff-f2f48163af16)
![image](https://github.com/user-attachments/assets/3f79ae10-9094-487d-af18-3289d8baf6ec)
![image](https://github.com/user-attachments/assets/b33aff56-d820-4e1d-9abe-0af251cdfbe7)

2024-09-25 04:07 UTC, Jihyeoniiiii commented on src/assets/images/user.png
넵 svg로 통일하겠습니다!

2024-09-25 04:12 UTC, Jihyeoniiiii commented on src/components/location-input.tsx
> +        ))}
네! 수정했습니다

2024-09-25 04:13 UTC, Jihyeoniiiii commented on src/components/location-input.tsx
> +              onChange={(e) => onChange(index, e)}
useRef 알아보고 사용해 보겠습니다

2024-09-25 04:23 UTC, Jihyeoniiiii commented on app/home/page.tsx
> +import { TMap } from '~/components/t-map'
네! 정리했습니다

2024-09-25 04:25 UTC, Jihyeoniiiii commented on src/components/location-permission-button.tsx
> +        onClick={onClick}
혹시 상위 컴포넌트에서 사용할 state가 있으면 커스텀훅으로 분리해서 작성해도 괜찮을까요?

2024-09-25 04:26 UTC, Jihyeoniiiii commented on app/home/page.tsx
> +    const appKey = 'TTlRjX8uuV5HqbcQObDKesvd32lp4L39MAVEi4ha'
넵 !

2024-10-14 07:48 UTC, wontory requested changes
해당 PR 이후로 변경사항이 많아서 한번 Pull 받아주신 후에 수정해주시면 좋을 것 같습니다!

2024-10-14 07:48 UTC, wontory commented on src/components/top-bar.tsx
top-bar 컴포넌트는 삭제해주시고(제가 마이페이지 작업하면서 추가해놨어요! -> site-header.tsx)
현재 home으로 잡혀있는 route는 root(`/`)로 변경해주세요!
(site-header를 포함한 레이아웃은 제가 만들어놔서 내용물만 옮겨주시면 될 것 같아요.)

2024-10-14 07:48 UTC, wontory commented on app/home/page.tsx
> +      </Link>
Link 안에 Button이 들어가면 접근성 면에서 좋지 않아요.
Link 컴포넌트의 className으로 `buttonVariants({variant:'secondary', size:'sm'})`를 넣어주면 button 스타일의 Link를 만들 수 있어요!

2024-10-14 07:48 UTC, wontory commented on src/components/popular-location-rank.tsx
location보다는 place가 더 이해하기 쉬울 것 같아요!
location은 x, y 좌표로 해석될 여지가 있어보입니다 :)
(`location-input`도 동일)

2024-10-14 07:48 UTC, wontory commented on src/hooks/use-location-permission.tsx
훅을 잘 만들어주신 것 같아요!
온보딩 페이지에 위치정보 허용에도 적용할 수 있을 것 같은데 수정해주실 수 있을까요?

2024-10-14 07:48 UTC, wontory commented on src/constants/route.ts
기획 수정으로 MAIN 경로는 `/`가 돼야해요.

2024-10-14 09:36 UTC, merged